// Auto-generated land/ocean bitmask, 256x128 equirectangular, packed 1 bit/px.
// Derived from a public earth-topology texture, downsampled and thresholded, then
// base64 encoded so the dotted globe ships its continents inline (no runtime fetch).
// x: 0..W maps to longitude -180..+180; y: 0..H maps to latitude +90..-90.

export const MASK_W = 256;
export const MASK_H = 128;

const MASK_B64 =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADgHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+P+H0f9/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGD8//7///8fAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAA4MMf/v///wMAAD8CAAAAAABgAAAAAAAAAAAAAAAAAAAA/OP/////AQAAHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD8wP////8DAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAgP///wMAAAAAAAAPAAAAcAAAAAAAAAAAAAAAAAAAoAEA////AQAAAAAAgAEAAAAAAAAAAAAAAAAAAAAAAADwBwD+//8AAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAEAA/AP7//wAAAAAAAAAAAAAAfgAIAAAAAAAAgB8AAgAAAPgA9v9/AAAA4AcAAAAAAP//AJwfAAAAAfD//6APAAAY4APw/x8AAAD4BwEAwACA/88Rfh8A8P0DAP/4wPkH4AGAD/z/AAAAAHwwAABAAID//x/+/4H//wBAnP8/8D8AAIAE/A8APgAAPgAAAAwAgP//B/z/9/8BAED6///PPwAAwAPwBwAeAAAfAAAABgCA//8D+P///wwAAPz//w3/AQCAAPADAAAA8A8AAAAGAAD+/8MA/v8vHwDA7v//D/4DABwAwAMAAADwBwAAAAYAAP7/93//f8AHAEAm+P9//gMAAAQAAAAAAHAAAAAABgAA/v////8+DAAAAAbA////BwAABgAAAAAAIAAAAAAGAAD8////DwAEAAAAAAD+//8HAHgPAAAAADAAAAAAAAYAAOD///8HAAcAAAAAAPz//wMA/A8AAAAAAAAAAAAABgDA/////wGABwAAAAAA+P//AQD8HwAAAAAAAAAAAAAHAPD/////AYADAAAAAADw///xAfx/AAAAAAAAAAAAAA8H4P////8FgAEAAAAAAOD///ED/D8AAAAAAMAAAAAAjz/8////8w0AAAAAAAAAwP//+wf+AAAAAAAA8P8NAACH///////nLQAAAAAAAACA/v///X/DAAAAAADwbwcAAIL//////z4OAAAAAAAAAAD////w/wEAAAAAAPgPBwAAgP////9/GAcAAAAAAAAAAP///4NhAAAAAAAA/ocHAAAA/v///38YAwAAAAAAAAAA////STwAAAAAAAC++AFwAADz////P7whAAAAAAAAAAD///8BHwAAAAAA/APzB+ADAP////9/HiAAAAAAAAAAgP//P8gHAAAAAAD8A8bD4wdg/v///z8PAAAAAAAAAAAA//8/+AEAAAAAAPxAyPD/A8D/////FwYQAAAAAAAAAAD9/x/AAAAAAAAA+ACI+f8Hwf////8DBBgAAAAAAAAAAPz/f/gAAAAAAABwAITx/9+3/////wEIDAAAAAAAAAAA+v8neAAAAAAAAAB/AIC8////////AQAGAAAAAAAAAAD8/wccAAAAAAAA8H8AAB7///////8AwAEAAAAAAAAAALD/AwAAAAAAAAD4DwAAPv7//////wAgAAAAAAAAAAAAIP8HAAAAAAAAAP6HAwA++P/D////BAAAAAAAAAAAAABg/wMAAAAAAAAA/scHgP/w/4P//38QAAAAAAAAAAAAAAD+AQAAAAAAAAD+/x/A//H/Av//fzIAAAAAAAAAAAAAAPwBAAAAAAAAAH//H8D+4/9w+P//OAAAAAAAAAAAAAAA+AEAAAAAAACAf/w/7/wH/nAA/v8fAAAAAAAAAAAAAADwAwAAAAAAAMC////f+YcA8Bfu/08AAAAAAAAAAAAAAPADAAAAAAAAwPz//4/xBwPgH/QfYAAAAAAAAAAAAAAA4AMAAAAAAACA7/////MHAuAX9AcAAAAAAAAAAAIAAADgBwAAAAAAAID/////9w8A8A70BwAAAAAAAAAAAgAAAMAPADAAAAAAgN///9/nHwDwDvAHAAAAAAAAAAAAAAAAAG8AAAAAAACAmf/P/89/APAF4A1gAAAAAAAAAAAAAAAA7AEAAAAAAADY/+f/zz8A8ABAGWAAAAAAAAAAAAAAAADADwAAAAAAAO77//+fDwDgAEA4AAAAAAAAAAAAAAAAAAAPAAAAAAAA/vD//58BAOAAQDAAAAAAAAAAAAAAAAAAAAAAAAAAAID/+P//fwAAwAAAMgAAAAAAAAAAAAAAAAAAGNgBAAAAwH/2////DwDAAAAAAAAAAAAAAAAAAAAAAAAweAAAAAAAP2f///8PAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAAAAAPif///wcAAAAAAAADAAAAAAAAAAAAAAAAAB4fAAAAAADA////AQAAAAAAAAEAAAAAAAAAAAAAAAAAHj8AAAAAAMD///8BAAAAMAEMAAAAAAAAAAAAAAAAAAAODgAAAAAAgP///wAAAAAwAQYAAAAAAAAAAAAAAAAAAAfOAwAAAACA//8fAAAAAEAABwAAAAAAAAAAAAAAAAAAA0IDAAAAAID//w8AAAAAwAAHAAAAAAAAAAAAAAAAAIABAAMAAAAAAP//DwAAAACAACFAAAAAAAAAAAAAAAAAgAEAAAAAAAAA//8PAAAAAIABcAAAAAAAAAAAAAAAAACAAQAAAAAAAAD+/w8AAAAAAANwgB8AAAAAAAAAAAAAAIABAAAMAAAAAP7/DwAAAAAABgAA/ggAAAAAAAAAAAAAgAMA2H0AAAAA/P8HAAAAAAAQAADgAQAAAAAAAAAAAACAA4DPfwAAAAD8/wcAAAAAANABAIABAAAAAAAAAAAAAAAXAM9/AAAAAPz/DwAAAAAAAAADAAMAAAAAAAAAAAAAAH/A5x8AAAAA/P8PAAAAAAAAAAAAAAAAAAAAAAAAAAAAPvDnDwAAAAD8/w8AAAAAAAAAAAAAAAAAAAAAAAAAAAD+4OcPAAAAAP7/DwwAAAAAAAAAAAAAAAAAAAAAAAAAAPzg9w8AAAAA/v8PDAAAAAAAAAAAAAAAAAAAAAAAAAAA+Bv/DwAAAAD+/wcMAAAAAAAABkAAAAAAAAAAAAAAAADgP/4HAAAAAP//AAcAAAAAAAAewAAAAAAAAAAAAAAAAMA//gcAAAAA/v8ABwAAAAAAABziAAAAAAAAAAAAAAAAwA//BwAAAAD+/wAHAAAAAAAA/s0AAAAAAAAAAAAAAADAB/8DAAAAAPx/gAMAAAAAAPj/iQIAAAAAAAAAAAAAAMAH/wEAAAAA/H+AAwAAAAAA/P+BAQAAAAAAAAAAAAAAwAc+AAAAAAD8fwADAAAAAAD8/4ADAAAAAAAAAAAAAADABx4AAAAAAPh/AAAAAAAAAPz/gA8AAAAAAAAAAAAAAMADHgAAAAAA+H8AAAAAAAAA/H8AGAAAAAAAAAAAAAAA4AMeAAAAAADwfwAAAAAAAAD8PwAYAAAAAAAAAAAAAADgBwAAAAAAAPA/AAAAAAAAAPgBABwAAAAAAAAAAAAAAOAHAAAAAAAA4B8AAAAAAAAA+AAEHgAAAAAAAAAAAAAA4AcAAAAAAADgDwAAAAAAAAA4AAQGAAAAAAAAAAAAAADgAwAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAOADAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAAAA8AMAAAAAAAAAAAAAAAAAAAAAAMADAAAAAAAAAAAAAADwAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAPABAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAA8AEAAAAAAAAAAAAAAAAAAAAAAIABAAwAAAAAAAAAAADwAQAAAAAAAAAAAAAAAAAAAAAAAAEABgAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAIADAAAAAAAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAgAEAAAAAAAAAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAADwAADA///D9z8AAAAAAAAAAAAAAAAAAwAAAAAAAAAA4P//Af///////wcAAAAAAAAAAAAAAGAPAAAAAAAAAID3///x/////////wMAAAAAAAAAAAAA4A8AAAAACP7///////j//////////wEAAAAAAAAAAAAAHwAAAAD/////////////////////AQAAAAAAAAD+//8fAAAA4P///////////////////38AAAAA9P///////wcAAAD4////////////////////DwAAAAD///////85AAAA/P////////////////////8PAAAA/////////wEAwID//////////////////////58AABDg////////AQDwAfj/////////////////////BwAAAAD8//////8DAADw//////////////////////8DAAAA8P////////8Af/7//////////////////////z8AAAAA/v///////////////////////////////////z//v+P//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////w==";

let bits: Uint8Array | null = null;
function unpack(): Uint8Array {
  if (bits) return bits;
  const bin =
    typeof atob === "function"
      ? atob(MASK_B64)
      : Buffer.from(MASK_B64, "base64").toString("binary");
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
  bits = arr;
  return arr;
}

/** True where the given latitude/longitude (degrees) falls on land. */
export function isLand(lat: number, lon: number): boolean {
  const b = unpack();
  let x = Math.floor(((lon + 180) / 360) * MASK_W);
  let y = Math.floor(((90 - lat) / 180) * MASK_H);
  if (x < 0) x = 0;
  else if (x >= MASK_W) x = MASK_W - 1;
  if (y < 0) y = 0;
  else if (y >= MASK_H) y = MASK_H - 1;
  const idx = y * MASK_W + x;
  return ((b[idx >> 3] >> (idx & 7)) & 1) === 1;
}
